glibc: nativesdk: fix ftbfs nativesdk-glibc
Building nativesdk-glibc failed because some binaries aren't installed.

ERROR: nativesdk-glibc-2.28-r0 do_package: QA Issue: nativesdk-glibc: Files/directories were installed but not shipped in any package:
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/getconf
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/iconv
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/pcprofiledump
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/pldd
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/getent
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/sprof
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/gencat
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/rpcgen
  /opt/emlinux/2.0/sysroots/x86_64-emlinuxsdk-linux/usr/bin/locale

Because line 6 and 7 changes package contens.

FILES_${PN}-utils_remove = "${sbindir}/*"
FILES_${PN}-utils += "${sbindir}/iconvconfig"

This patch remove these lines to create package without modify.