libpcap: Fix patch fuzz error in libpcap-pkgconfig-support.patch
This commit fixes following patch fuzz detected error.

ERROR: libpcap-1.8.1-r0 do_patch: Fuzz detected:

Applying patch libpcap-pkgconfig-support.patch
patching file Makefile.in
Hunk #1 succeeded at 69 with fuzz 1 (offset 1 line).
patching file configure.ac
patching file libpcap.pc.in

The context lines in the patches can be updated with devtool:

    devtool modify libpcap
    devtool finish --force-patch-refresh libpcap <layer_path>

Don't forget to review changes done by devtool!

ERROR: libpcap-1.8.1-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

The libpcap-pkgconfig-support.patch patch applied after do_debian_patch task,
so this changes cleanly apply to libpcap source which based on debian source.

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>