xml-core: add RDEPENDS_${PN}="perl"
This fixes the following error:
```
ERROR: xml-core-0.18+nmu1-r0 do_package_qa: QA Issue:
/usr/sbin/update-xmlcatalog contained in package xml-core requires
/usr/bin/perl, but no providers found in RDEPENDS_xml-core? [file-rdeps]
```